name: github pages

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
       working-directory: ./my-react-app
       SUPER_SECRET: ${{ secrets.SuperSecret }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
        working-directory: ${{env.working-directory}}
      - run: npm run build
        working-directory: ${{env.working-directory}}
      
      - run: npm i gh-pages --save-dev
        working-directory: ${{env.working-directory}}
      - run: git config --local user.email ${{ secrets.SuperSecret }}
        working-directory: ${{env.working-directory}}
      - run: git config --local user.name ${{ secrets.SuperSecret }}
        working-directory: ${{env.working-directory}}
      - run: git config --global credential.helper wincred
        working-directory: ${{env.working-directory}}
      - run: npm run deploy
        working-directory: ${{env.working-directory}}
      - run: gh-pages -d build
        working-directory: ${{env.working-directory}}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/develop'
        with:
          github_token: ${{secrets.GITHUB_TOKEN }}
          publish_dir: ./my-react-app
