name: React app deployement

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: deploy
      run: |
        npm i gh-pages
        npm build
        gh-pages -d build
      working-directory: my-react-app
