name: React

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
name: React app deployement

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
      working-directory: ./my-react-app
